### ISSUE TITLE
Inconsistent colors?

### ISSUE THREAD

**Issue by LynXHashib** [danihek/hellwal#2]
I generated colors with 2 of the wallpaper you used and the color palette are a lot different. Thats not a problem but the problem is terminal colors are unbearable, cant see half the thing

**Comment by danihek** [comment]
Well, I use terminal all the time and I don't have this issue. Do you have this problem with one particular wallpaper or it's common with others too?
Can you send me wallpaper to play with, so I can adjust colors a little if it's needed?

Also next release will contain new cmd line argument ``--bright-offset``, so you can adjust brightness without losing color palette
