### ISSUE TITLE
Nix package?

### ISSUE THREAD

**Issue by Vaisakhkm2625** [danihek/hellwal#4]
:) great project.. hope it will grow like pywal (or wallust)...

i came here to ask if there is any nix flake off this..

**Comment by danihek** [comment]
Hi! Thank you!

I create pull request to add hellwal to nixpkgs:
https://github.com/NixOS/nixpkgs/pull/364360

we will see how it goes, I never tried that

**Comment by danihek** [comment]
It's merged! 🎉

**Comment by Vaisakhkm2625** [comment]
> It's merged! 🎉

:) THANKS...
